version: 2.1

orbs:
  # Always take the latest version of the orb, this allows us to
  # run specs against Solidus supported versions only without the need
  # to change this configuration every time a Solidus version is released
  # or goes EOL.
  solidusio_extensions: solidusio/extensions@volatile

executors:
  # We don't rely directly on the DB, but we still want to ensure generated
  # extensions are able to connect and spin up Solidus. Using an in-memory
  # SQLite makes it blazingly fast.
  sqlite-memory:
    docker:
       - image: circleci/ruby:2.5.6-node-browsers
         environment:
           RAILS_ENV: test
           DB: sqlite
           DATABASE_URL: sqlite3::memory:?pool=1
           DATABASE_CLEANER_ALLOW_REMOTE_DATABASE_URL: true

jobs:
  solidus-master:
    executor: sqlite-memory
    steps: ['checkout', 'solidusio_extensions/run-tests-solidus-master']
  solidus-current:
    executor: sqlite-memory
    steps: ['checkout', 'solidusio_extensions/run-tests-solidus-current']
  solidus-older:
    executor: sqlite-memory
    steps: ['checkout', 'solidusio_extensions/run-tests-solidus-older']

workflows:
  "Run specs on supported Solidus versions":
    jobs:
      - solidus-master
      - solidus-current
      - solidus-older

  "Weekly run specs against master":
    triggers:
      - schedule:
          cron: "0 0 * * 4" # every Thursday
          filters:
            branches:
              only:
                - master
    jobs:
      - solidus-master
      - solidus-current
      - solidus-older
