version: 2.1

orbs:
  # Always take the latest version of the orb, this allows us to
  # run specs against Solidus supported versions only without the need
  # to change this configuration every time a Solidus version is released
  # or goes EOL.
  solidusio_extensions: solidusio/extensions@volatile
  slack: circleci/slack@4.9.3

commands:
  setup:
    steps:
      - checkout
      - run:
          name: "Update bundler"
          command: |
            sudo gem update --system
            gem --version
            gem install bundler -v '>=2.3.21' --conservative
            bundle --version

  notify:
    steps:
      - slack/notify:
          event: fail
          template: basic_fail_1
          branch_pattern: master

jobs:
  solidus-master:
    executor: solidusio_extensions/sqlite
    steps: ['setup', 'solidusio_extensions/run-tests-solidus-master', 'notify']
  solidus-current:
    executor: solidusio_extensions/sqlite
    steps: ['setup', 'solidusio_extensions/run-tests-solidus-current', 'notify']
  solidus-older:
    executor: solidusio_extensions/sqlite
    steps: ['setup', 'solidusio_extensions/run-tests-solidus-older', 'notify']
  lint-code:
    executor: solidusio_extensions/sqlite
    steps: ['setup', 'solidusio_extensions/lint-code', 'notify']

workflows:
  "Run specs on supported Solidus versions":
    jobs:
      - solidus-master:
          context: slack-secrets
      - solidus-current:
          context: slack-secrets
      - solidus-older:
          context: slack-secrets
      - lint-code:
          context: slack-secrets

  "Weekly run specs against master":
    triggers:
      - schedule:
          cron: "0 0 * * 4" # every Thursday
          filters:
            branches:
              only:
                - master
    jobs:
      - solidus-master:
          context: slack-secrets
      - solidus-current:
          context: slack-secrets
      - solidus-older:
          context: slack-secrets
